# Should be books updated every time they are opened?
update-books-on-use: true

# Book to open to a player when he joins the server
open-book-on-join: ''

# Book to open to a player when he joins the server the first time
open-book-on-first-join: ''

# Books given to the players when they joins the server
books-on-join: []

# Books given to the players when they joins the server the first time
books-on-first-join: []