name: ${name}
main: net.socialhangover.net.InteractiveBooksPlugin
version: ${version}
api-version: 1.16
description: ${description}
authors: ["Leonardo_DGS", "calumari"]
website: ${url}
depend: [helper]
softdepend: [PlaceholderAPI]