name: ${name}
main: net.leonardo_dgs.interactivebooks.InteractiveBooks
version: ${version}
api-version: 1.15
description: ${description}
author: "Leonardo_DGS"
website: ${url}
softdepend: [PlaceholderAPI, helper]
commands:
  ibooks:
    description: Command to manage books
    permission: interactivebooks.command
    aliases: [interactivebooks, ib]